// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetWorld.Infrastructure.Persistence;

#nullable disable

namespace PetWorld.Infrastructure.Migrations
{
    [DbContext(typeof(PetWorldDbContext))]
    [Migration("20260208225446_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PetWorld.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IterationCount")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("PetWorld.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bf43c6c-2c24-4d82-9c2f-05a1e7c49a06"),
                            Category = 1,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium karma dla dorosłych psów średnich ras",
                            Name = "Royal Canin Adult Dog 15kg"
                        },
                        new
                        {
                            Id = new Guid("3a7c1ad6-6fb4-4f9a-9a2d-7c11df74e6ff"),
                            Category = 2,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sucha karma dla dorosłych kotów z kurczakiem",
                            Name = "Whiskas Adult Kurczak 7kg"
                        },
                        new
                        {
                            Id = new Guid("e3fa1b9b-3758-46f1-8f3a-5f0c9a2a0e9e"),
                            Category = 3,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uzdatniacz wody do akwarium, neutralizuje chlor",
                            Name = "Tetra AquaSafe 500ml"
                        },
                        new
                        {
                            Id = new Guid("f2a39b45-1f77-4c0b-a4b1-8a6b5d2c9a18"),
                            Category = 4,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wysoki drapak z platformami i domkiem",
                            Name = "Trixie Drapak XL 150cm"
                        },
                        new
                        {
                            Id = new Guid("4e2f0a6b-8c17-4c65-96f1-1d7f0b5a2c3e"),
                            Category = 5,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wytrzymała zabawka do napełniania smakołykami",
                            Name = "Kong Classic Large"
                        },
                        new
                        {
                            Id = new Guid("9b1f4d62-9f6e-4b0e-8f42-4b2c7c4e2e6a"),
                            Category = 6,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Klatka 60x40cm z wyposażeniem",
                            Name = "Ferplast Klatka dla chomika"
                        },
                        new
                        {
                            Id = new Guid("1ac2d2c4-8e26-4d1f-9a0a-93db3f5e2b79"),
                            Category = 7,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smycz zwijana dla psów do 50kg",
                            Name = "Flexi Smycz automatyczna 8m"
                        },
                        new
                        {
                            Id = new Guid("2b5a69fd-4d44-4c32-bf5d-7f6b2a5d7f31"),
                            Category = 2,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Karma dla kociąt do 12 miesiąca życia",
                            Name = "Brit Premium Kitten 8kg"
                        },
                        new
                        {
                            Id = new Guid("4c6f2a1b-5e7a-45ad-8b2f-63e2c9b1a7a4"),
                            Category = 3,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kompletny zestaw CO2 dla roślin akwariowych",
                            Name = "JBL ProFlora CO2 Set"
                        },
                        new
                        {
                            Id = new Guid("5ad1d7e0-6d9c-4c0c-bf9a-0d84e2b2f4ef"),
                            Category = 6,
                            CreatedAt = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Naturalne siano łąkowe, podstawa diety",
                            Name = "Vitapol Siano dla królików 1kg"
                        });
                });

            modelBuilder.Entity("PetWorld.Domain.Entities.Product", b =>
                {
                    b.OwnsOne("PetWorld.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasData(
                                new
                                {
                                    ProductId = new Guid("6bf43c6c-2c24-4d82-9c2f-05a1e7c49a06"),
                                    Amount = 289m,
                                    Currency = "PLN"
                                },
                                new
                                {
                                    ProductId = new Guid("3a7c1ad6-6fb4-4f9a-9a2d-7c11df74e6ff"),
                                    Amount = 129m,
                                    Currency = "PLN"
                                },
                                new
                                {
                                    ProductId = new Guid("e3fa1b9b-3758-46f1-8f3a-5f0c9a2a0e9e"),
                                    Amount = 45m,
                                    Currency = "PLN"
                                },
                                new
                                {
                                    ProductId = new Guid("f2a39b45-1f77-4c0b-a4b1-8a6b5d2c9a18"),
                                    Amount = 399m,
                                    Currency = "PLN"
                                },
                                new
                                {
                                    ProductId = new Guid("4e2f0a6b-8c17-4c65-96f1-1d7f0b5a2c3e"),
                                    Amount = 69m,
                                    Currency = "PLN"
                                },
                                new
                                {
                                    ProductId = new Guid("9b1f4d62-9f6e-4b0e-8f42-4b2c7c4e2e6a"),
                                    Amount = 189m,
                                    Currency = "PLN"
                                },
                                new
                                {
                                    ProductId = new Guid("1ac2d2c4-8e26-4d1f-9a0a-93db3f5e2b79"),
                                    Amount = 119m,
                                    Currency = "PLN"
                                },
                                new
                                {
                                    ProductId = new Guid("2b5a69fd-4d44-4c32-bf5d-7f6b2a5d7f31"),
                                    Amount = 159m,
                                    Currency = "PLN"
                                },
                                new
                                {
                                    ProductId = new Guid("4c6f2a1b-5e7a-45ad-8b2f-63e2c9b1a7a4"),
                                    Amount = 549m,
                                    Currency = "PLN"
                                },
                                new
                                {
                                    ProductId = new Guid("5ad1d7e0-6d9c-4c0c-bf9a-0d84e2b2f4ef"),
                                    Amount = 25m,
                                    Currency = "PLN"
                                });
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
